/* news.c generated by valac 0.34.9, the Vala compiler
 * generated from news.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>
#include <stdio.h>
#include <gtk/gtk.h>
#include <float.h>
#include <math.h>
#include <gdk/gdk.h>


#define TYPE_ARTICLE (article_get_type ())
typedef struct _Article Article;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
typedef struct _Block1Data Block1Data;

struct _Article {
	gchar* title;
	gchar* text;
	gchar* link;
};

struct _Block1Data {
	int _ref_count_;
	Article article;
	GPid child_pid;
};



GType article_get_type (void) G_GNUC_CONST;
Article* article_dup (const Article* self);
void article_free (Article* self);
void article_copy (const Article* self, Article* dest);
void article_destroy (Article* self);
Article* fetch_news (int* result_length1);
static void _vala_array_add1 (Article** array, int* length, int* size, const Article* value);
static void _vala_Article_array_free (Article* array, gint array_length);
gint _vala_main (const gchar* args, int args_length1);
static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
static gboolean _____lambda4_ (Block1Data* _data1_, GdkEventButton* e);
static gboolean ______lambda4__gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


void article_copy (const Article* self, Article* dest) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	gchar* _tmp5_ = NULL;
#line 1 "/home/allen/Projects/news/src/news.vala"
	_tmp0_ = (*self).title;
#line 1 "/home/allen/Projects/news/src/news.vala"
	_tmp1_ = g_strdup (_tmp0_);
#line 1 "/home/allen/Projects/news/src/news.vala"
	_g_free0 ((*dest).title);
#line 1 "/home/allen/Projects/news/src/news.vala"
	(*dest).title = _tmp1_;
#line 1 "/home/allen/Projects/news/src/news.vala"
	_tmp2_ = (*self).text;
#line 1 "/home/allen/Projects/news/src/news.vala"
	_tmp3_ = g_strdup (_tmp2_);
#line 1 "/home/allen/Projects/news/src/news.vala"
	_g_free0 ((*dest).text);
#line 1 "/home/allen/Projects/news/src/news.vala"
	(*dest).text = _tmp3_;
#line 1 "/home/allen/Projects/news/src/news.vala"
	_tmp4_ = (*self).link;
#line 1 "/home/allen/Projects/news/src/news.vala"
	_tmp5_ = g_strdup (_tmp4_);
#line 1 "/home/allen/Projects/news/src/news.vala"
	_g_free0 ((*dest).link);
#line 1 "/home/allen/Projects/news/src/news.vala"
	(*dest).link = _tmp5_;
#line 91 "news.c"
}


void article_destroy (Article* self) {
#line 2 "/home/allen/Projects/news/src/news.vala"
	_g_free0 ((*self).title);
#line 3 "/home/allen/Projects/news/src/news.vala"
	_g_free0 ((*self).text);
#line 4 "/home/allen/Projects/news/src/news.vala"
	_g_free0 ((*self).link);
#line 102 "news.c"
}


Article* article_dup (const Article* self) {
	Article* dup;
#line 1 "/home/allen/Projects/news/src/news.vala"
	dup = g_new0 (Article, 1);
#line 1 "/home/allen/Projects/news/src/news.vala"
	article_copy (self, dup);
#line 1 "/home/allen/Projects/news/src/news.vala"
	return dup;
#line 114 "news.c"
}


void article_free (Article* self) {
#line 1 "/home/allen/Projects/news/src/news.vala"
	article_destroy (self);
#line 1 "/home/allen/Projects/news/src/news.vala"
	g_free (self);
#line 123 "news.c"
}


GType article_get_type (void) {
	static volatile gsize article_type_id__volatile = 0;
	if (g_once_init_enter (&article_type_id__volatile)) {
		GType article_type_id;
		article_type_id = g_boxed_type_register_static ("Article", (GBoxedCopyFunc) article_dup, (GBoxedFreeFunc) article_free);
		g_once_init_leave (&article_type_id__volatile, article_type_id);
	}
	return article_type_id__volatile;
}


static gint string_index_of (const gchar* self, const gchar* needle, gint start_index) {
	gint result = 0;
	gchar* _result_ = NULL;
	gint _tmp0_ = 0;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
#line 995 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, 0);
#line 995 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	g_return_val_if_fail (needle != NULL, 0);
#line 996 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp0_ = start_index;
#line 996 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp1_ = needle;
#line 996 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp2_ = strstr (((gchar*) self) + _tmp0_, (gchar*) _tmp1_);
#line 996 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_result_ = _tmp2_;
#line 998 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp3_ = _result_;
#line 998 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	if (_tmp3_ != NULL) {
#line 161 "news.c"
		gchar* _tmp4_ = NULL;
#line 999 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp4_ = _result_;
#line 999 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		result = (gint) (_tmp4_ - ((gchar*) self));
#line 999 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		return result;
#line 169 "news.c"
	} else {
#line 1001 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		result = -1;
#line 1001 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		return result;
#line 175 "news.c"
	}
}


static gchar* string_slice (const gchar* self, glong start, glong end) {
	gchar* result = NULL;
	glong string_length = 0L;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	glong _tmp2_ = 0L;
	glong _tmp5_ = 0L;
	gboolean _tmp8_ = FALSE;
	glong _tmp9_ = 0L;
	gboolean _tmp12_ = FALSE;
	glong _tmp13_ = 0L;
	glong _tmp16_ = 0L;
	glong _tmp17_ = 0L;
	glong _tmp18_ = 0L;
	glong _tmp19_ = 0L;
	glong _tmp20_ = 0L;
	gchar* _tmp21_ = NULL;
#line 1336 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1337 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp0_ = strlen (self);
#line 1337 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp1_ = _tmp0_;
#line 1337 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	string_length = (glong) _tmp1_;
#line 1338 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp2_ = start;
#line 1338 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	if (_tmp2_ < ((glong) 0)) {
#line 209 "news.c"
		glong _tmp3_ = 0L;
		glong _tmp4_ = 0L;
#line 1339 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp3_ = string_length;
#line 1339 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp4_ = start;
#line 1339 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		start = _tmp3_ + _tmp4_;
#line 218 "news.c"
	}
#line 1341 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp5_ = end;
#line 1341 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	if (_tmp5_ < ((glong) 0)) {
#line 224 "news.c"
		glong _tmp6_ = 0L;
		glong _tmp7_ = 0L;
#line 1342 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp6_ = string_length;
#line 1342 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp7_ = end;
#line 1342 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		end = _tmp6_ + _tmp7_;
#line 233 "news.c"
	}
#line 1344 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp9_ = start;
#line 1344 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	if (_tmp9_ >= ((glong) 0)) {
#line 239 "news.c"
		glong _tmp10_ = 0L;
		glong _tmp11_ = 0L;
#line 1344 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp10_ = start;
#line 1344 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp11_ = string_length;
#line 1344 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp8_ = _tmp10_ <= _tmp11_;
#line 248 "news.c"
	} else {
#line 1344 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp8_ = FALSE;
#line 252 "news.c"
	}
#line 1344 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	g_return_val_if_fail (_tmp8_, NULL);
#line 1345 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp13_ = end;
#line 1345 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	if (_tmp13_ >= ((glong) 0)) {
#line 260 "news.c"
		glong _tmp14_ = 0L;
		glong _tmp15_ = 0L;
#line 1345 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp14_ = end;
#line 1345 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp15_ = string_length;
#line 1345 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp12_ = _tmp14_ <= _tmp15_;
#line 269 "news.c"
	} else {
#line 1345 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp12_ = FALSE;
#line 273 "news.c"
	}
#line 1345 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	g_return_val_if_fail (_tmp12_, NULL);
#line 1346 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp16_ = start;
#line 1346 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp17_ = end;
#line 1346 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	g_return_val_if_fail (_tmp16_ <= _tmp17_, NULL);
#line 1347 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp18_ = start;
#line 1347 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp19_ = end;
#line 1347 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp20_ = start;
#line 1347 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	_tmp21_ = g_strndup (((gchar*) self) + _tmp18_, (gsize) (_tmp19_ - _tmp20_));
#line 1347 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	result = _tmp21_;
#line 1347 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	return result;
#line 295 "news.c"
}


static gchar* string_replace (const gchar* self, const gchar* old, const gchar* replacement) {
	gchar* result = NULL;
	GError * _inner_error_ = NULL;
#line 1388 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	g_return_val_if_fail (self != NULL, NULL);
#line 1388 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	g_return_val_if_fail (old != NULL, NULL);
#line 1388 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	g_return_val_if_fail (replacement != NULL, NULL);
#line 308 "news.c"
	{
		GRegex* regex = NULL;
		const gchar* _tmp0_ = NULL;
		gchar* _tmp1_ = NULL;
		gchar* _tmp2_ = NULL;
		GRegex* _tmp3_ = NULL;
		GRegex* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		GRegex* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		gchar* _tmp8_ = NULL;
		gchar* _tmp9_ = NULL;
#line 1390 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp0_ = old;
#line 1390 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp1_ = g_regex_escape_string (_tmp0_, -1);
#line 1390 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp2_ = _tmp1_;
#line 1390 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp3_ = g_regex_new (_tmp2_, 0, 0, &_inner_error_);
#line 1390 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp4_ = _tmp3_;
#line 1390 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_g_free0 (_tmp2_);
#line 1390 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		regex = _tmp4_;
#line 1390 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 1390 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
			if (_inner_error_->domain == G_REGEX_ERROR) {
#line 339 "news.c"
				goto __catch2_g_regex_error;
			}
#line 1390 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 1390 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
			g_clear_error (&_inner_error_);
#line 1390 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
			return NULL;
#line 348 "news.c"
		}
#line 1391 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp6_ = regex;
#line 1391 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp7_ = replacement;
#line 1391 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp8_ = g_regex_replace_literal (_tmp6_, self, (gssize) -1, 0, _tmp7_, 0, &_inner_error_);
#line 1391 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp5_ = _tmp8_;
#line 1391 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 1391 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
			_g_regex_unref0 (regex);
#line 1391 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
			if (_inner_error_->domain == G_REGEX_ERROR) {
#line 364 "news.c"
				goto __catch2_g_regex_error;
			}
#line 1391 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
			_g_regex_unref0 (regex);
#line 1391 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 1391 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
			g_clear_error (&_inner_error_);
#line 1391 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
			return NULL;
#line 375 "news.c"
		}
#line 1391 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp9_ = _tmp5_;
#line 1391 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_tmp5_ = NULL;
#line 1391 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		result = _tmp9_;
#line 1391 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_g_free0 (_tmp5_);
#line 1391 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_g_regex_unref0 (regex);
#line 1391 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		return result;
#line 389 "news.c"
	}
	goto __finally2;
	__catch2_g_regex_error:
	{
		GError* e = NULL;
#line 1389 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		e = _inner_error_;
#line 1389 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_inner_error_ = NULL;
#line 1393 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		g_assert_not_reached ();
#line 1389 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		_g_error_free0 (e);
#line 403 "news.c"
	}
	__finally2:
#line 1389 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 1389 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 1389 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		g_clear_error (&_inner_error_);
#line 1389 "/usr/share/vala-0.34/vapi/glib-2.0.vapi"
		return NULL;
#line 414 "news.c"
	}
}


static void _vala_array_add1 (Article** array, int* length, int* size, const Article* value) {
#line 61 "/home/allen/Projects/news/src/news.vala"
	if ((*length) == (*size)) {
#line 61 "/home/allen/Projects/news/src/news.vala"
		*size = (*size) ? (2 * (*size)) : 4;
#line 61 "/home/allen/Projects/news/src/news.vala"
		*array = g_renew (Article, *array, *size);
#line 426 "news.c"
	}
#line 61 "/home/allen/Projects/news/src/news.vala"
	(*array)[(*length)++] = *value;
#line 430 "news.c"
}


static void _vala_Article_array_free (Article* array, gint array_length) {
#line 7 "/home/allen/Projects/news/src/news.vala"
	if (array != NULL) {
#line 437 "news.c"
		int i;
#line 7 "/home/allen/Projects/news/src/news.vala"
		for (i = 0; i < array_length; i = i + 1) {
#line 7 "/home/allen/Projects/news/src/news.vala"
			article_destroy (&array[i]);
#line 443 "news.c"
		}
	}
#line 7 "/home/allen/Projects/news/src/news.vala"
	g_free (array);
#line 448 "news.c"
}


Article* fetch_news (int* result_length1) {
	Article* result = NULL;
	GFile* youtube_page = NULL;
	GFile* _tmp0_ = NULL;
	GDataInputStream* data_stream = NULL;
	GDataInputStream* _tmp10_ = NULL;
	gchar* line = NULL;
	GString* text = NULL;
	GString* _tmp11_ = NULL;
	gchar* str = NULL;
	GString* _tmp21_ = NULL;
	const gchar* _tmp22_ = NULL;
	gchar* _tmp23_ = NULL;
	gint itemIndex = 0;
	Article* articles = NULL;
	Article* _tmp24_ = NULL;
	gint articles_length1 = 0;
	gint _articles_size_ = 0;
	Article* _tmp111_ = NULL;
	gint _tmp111__length1 = 0;
	GError * _inner_error_ = NULL;
#line 8 "/home/allen/Projects/news/src/news.vala"
	_tmp0_ = g_file_new_for_uri ("https://news.google.com/news/?ned=us&hl=en&output=rss");
#line 8 "/home/allen/Projects/news/src/news.vala"
	youtube_page = _tmp0_;
#line 10 "/home/allen/Projects/news/src/news.vala"
	data_stream = NULL;
#line 479 "news.c"
	{
		GFileInputStream* _tmp1_ = NULL;
		GFile* _tmp2_ = NULL;
		GFileInputStream* _tmp3_ = NULL;
		GDataInputStream* _tmp4_ = NULL;
#line 12 "/home/allen/Projects/news/src/news.vala"
		_tmp2_ = youtube_page;
#line 12 "/home/allen/Projects/news/src/news.vala"
		_tmp3_ = g_file_read (_tmp2_, NULL, &_inner_error_);
#line 12 "/home/allen/Projects/news/src/news.vala"
		_tmp1_ = _tmp3_;
#line 12 "/home/allen/Projects/news/src/news.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 493 "news.c"
			goto __catch0_g_error;
		}
#line 12 "/home/allen/Projects/news/src/news.vala"
		_tmp4_ = g_data_input_stream_new ((GInputStream*) _tmp1_);
#line 12 "/home/allen/Projects/news/src/news.vala"
		_g_object_unref0 (data_stream);
#line 12 "/home/allen/Projects/news/src/news.vala"
		data_stream = _tmp4_;
#line 11 "/home/allen/Projects/news/src/news.vala"
		_g_object_unref0 (_tmp1_);
#line 504 "news.c"
	}
	goto __finally0;
	__catch0_g_error:
	{
		GError* err = NULL;
		FILE* _tmp5_ = NULL;
		GError* _tmp6_ = NULL;
		const gchar* _tmp7_ = NULL;
		FILE* _tmp8_ = NULL;
		Article* _tmp9_ = NULL;
		gint _tmp9__length1 = 0;
#line 11 "/home/allen/Projects/news/src/news.vala"
		err = _inner_error_;
#line 11 "/home/allen/Projects/news/src/news.vala"
		_inner_error_ = NULL;
#line 14 "/home/allen/Projects/news/src/news.vala"
		_tmp5_ = stdout;
#line 14 "/home/allen/Projects/news/src/news.vala"
		_tmp6_ = err;
#line 14 "/home/allen/Projects/news/src/news.vala"
		_tmp7_ = _tmp6_->message;
#line 14 "/home/allen/Projects/news/src/news.vala"
		fputs (_tmp7_, _tmp5_);
#line 15 "/home/allen/Projects/news/src/news.vala"
		_tmp8_ = stdout;
#line 15 "/home/allen/Projects/news/src/news.vala"
		fputc ('\n', _tmp8_);
#line 16 "/home/allen/Projects/news/src/news.vala"
		_tmp9_ = NULL;
#line 16 "/home/allen/Projects/news/src/news.vala"
		_tmp9__length1 = 0;
#line 16 "/home/allen/Projects/news/src/news.vala"
		if (result_length1) {
#line 16 "/home/allen/Projects/news/src/news.vala"
			*result_length1 = _tmp9__length1;
#line 540 "news.c"
		}
#line 16 "/home/allen/Projects/news/src/news.vala"
		result = _tmp9_;
#line 16 "/home/allen/Projects/news/src/news.vala"
		_g_error_free0 (err);
#line 16 "/home/allen/Projects/news/src/news.vala"
		_g_object_unref0 (data_stream);
#line 16 "/home/allen/Projects/news/src/news.vala"
		_g_object_unref0 (youtube_page);
#line 16 "/home/allen/Projects/news/src/news.vala"
		return result;
#line 552 "news.c"
	}
	__finally0:
#line 11 "/home/allen/Projects/news/src/news.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 11 "/home/allen/Projects/news/src/news.vala"
		_g_object_unref0 (data_stream);
#line 11 "/home/allen/Projects/news/src/news.vala"
		_g_object_unref0 (youtube_page);
#line 11 "/home/allen/Projects/news/src/news.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 11 "/home/allen/Projects/news/src/news.vala"
		g_clear_error (&_inner_error_);
#line 11 "/home/allen/Projects/news/src/news.vala"
		return NULL;
#line 567 "news.c"
	}
#line 18 "/home/allen/Projects/news/src/news.vala"
	_tmp10_ = data_stream;
#line 18 "/home/allen/Projects/news/src/news.vala"
	g_data_input_stream_set_byte_order (_tmp10_, G_DATA_STREAM_BYTE_ORDER_LITTLE_ENDIAN);
#line 20 "/home/allen/Projects/news/src/news.vala"
	line = NULL;
#line 21 "/home/allen/Projects/news/src/news.vala"
	_tmp11_ = g_string_new ("");
#line 21 "/home/allen/Projects/news/src/news.vala"
	text = _tmp11_;
#line 579 "news.c"
	{
#line 23 "/home/allen/Projects/news/src/news.vala"
		while (TRUE) {
#line 583 "news.c"
			gchar* _tmp12_ = NULL;
			GDataInputStream* _tmp13_ = NULL;
			gchar* _tmp14_ = NULL;
			gchar* _tmp15_ = NULL;
			const gchar* _tmp16_ = NULL;
			GString* _tmp17_ = NULL;
			const gchar* _tmp18_ = NULL;
			GString* _tmp19_ = NULL;
#line 23 "/home/allen/Projects/news/src/news.vala"
			_tmp13_ = data_stream;
#line 23 "/home/allen/Projects/news/src/news.vala"
			_tmp14_ = g_data_input_stream_read_line (_tmp13_, NULL, NULL, &_inner_error_);
#line 23 "/home/allen/Projects/news/src/news.vala"
			_tmp12_ = _tmp14_;
#line 23 "/home/allen/Projects/news/src/news.vala"
			if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 23 "/home/allen/Projects/news/src/news.vala"
				if (_inner_error_->domain == G_IO_ERROR) {
#line 602 "news.c"
					goto __catch1_g_io_error;
				}
#line 23 "/home/allen/Projects/news/src/news.vala"
				_g_string_free0 (text);
#line 23 "/home/allen/Projects/news/src/news.vala"
				_g_free0 (line);
#line 23 "/home/allen/Projects/news/src/news.vala"
				_g_object_unref0 (data_stream);
#line 23 "/home/allen/Projects/news/src/news.vala"
				_g_object_unref0 (youtube_page);
#line 23 "/home/allen/Projects/news/src/news.vala"
				g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 23 "/home/allen/Projects/news/src/news.vala"
				g_clear_error (&_inner_error_);
#line 23 "/home/allen/Projects/news/src/news.vala"
				return NULL;
#line 619 "news.c"
			}
#line 23 "/home/allen/Projects/news/src/news.vala"
			_tmp15_ = _tmp12_;
#line 23 "/home/allen/Projects/news/src/news.vala"
			_tmp12_ = NULL;
#line 23 "/home/allen/Projects/news/src/news.vala"
			_g_free0 (line);
#line 23 "/home/allen/Projects/news/src/news.vala"
			line = _tmp15_;
#line 23 "/home/allen/Projects/news/src/news.vala"
			_tmp16_ = line;
#line 23 "/home/allen/Projects/news/src/news.vala"
			if (!(_tmp16_ != NULL)) {
#line 23 "/home/allen/Projects/news/src/news.vala"
				_g_free0 (_tmp12_);
#line 23 "/home/allen/Projects/news/src/news.vala"
				break;
#line 637 "news.c"
			}
#line 24 "/home/allen/Projects/news/src/news.vala"
			_tmp17_ = text;
#line 24 "/home/allen/Projects/news/src/news.vala"
			_tmp18_ = line;
#line 24 "/home/allen/Projects/news/src/news.vala"
			g_string_append (_tmp17_, _tmp18_);
#line 25 "/home/allen/Projects/news/src/news.vala"
			_tmp19_ = text;
#line 25 "/home/allen/Projects/news/src/news.vala"
			g_string_append_c (_tmp19_, '\n');
#line 23 "/home/allen/Projects/news/src/news.vala"
			_g_free0 (_tmp12_);
#line 651 "news.c"
		}
	}
	goto __finally1;
	__catch1_g_io_error:
	{
		GError* err = NULL;
		Article* _tmp20_ = NULL;
		gint _tmp20__length1 = 0;
#line 22 "/home/allen/Projects/news/src/news.vala"
		err = _inner_error_;
#line 22 "/home/allen/Projects/news/src/news.vala"
		_inner_error_ = NULL;
#line 28 "/home/allen/Projects/news/src/news.vala"
		_tmp20_ = NULL;
#line 28 "/home/allen/Projects/news/src/news.vala"
		_tmp20__length1 = 0;
#line 28 "/home/allen/Projects/news/src/news.vala"
		if (result_length1) {
#line 28 "/home/allen/Projects/news/src/news.vala"
			*result_length1 = _tmp20__length1;
#line 672 "news.c"
		}
#line 28 "/home/allen/Projects/news/src/news.vala"
		result = _tmp20_;
#line 28 "/home/allen/Projects/news/src/news.vala"
		_g_error_free0 (err);
#line 28 "/home/allen/Projects/news/src/news.vala"
		_g_string_free0 (text);
#line 28 "/home/allen/Projects/news/src/news.vala"
		_g_free0 (line);
#line 28 "/home/allen/Projects/news/src/news.vala"
		_g_object_unref0 (data_stream);
#line 28 "/home/allen/Projects/news/src/news.vala"
		_g_object_unref0 (youtube_page);
#line 28 "/home/allen/Projects/news/src/news.vala"
		return result;
#line 688 "news.c"
	}
	__finally1:
#line 22 "/home/allen/Projects/news/src/news.vala"
	if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 22 "/home/allen/Projects/news/src/news.vala"
		_g_string_free0 (text);
#line 22 "/home/allen/Projects/news/src/news.vala"
		_g_free0 (line);
#line 22 "/home/allen/Projects/news/src/news.vala"
		_g_object_unref0 (data_stream);
#line 22 "/home/allen/Projects/news/src/news.vala"
		_g_object_unref0 (youtube_page);
#line 22 "/home/allen/Projects/news/src/news.vala"
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 22 "/home/allen/Projects/news/src/news.vala"
		g_clear_error (&_inner_error_);
#line 22 "/home/allen/Projects/news/src/news.vala"
		return NULL;
#line 707 "news.c"
	}
#line 31 "/home/allen/Projects/news/src/news.vala"
	_tmp21_ = text;
#line 31 "/home/allen/Projects/news/src/news.vala"
	_tmp22_ = _tmp21_->str;
#line 31 "/home/allen/Projects/news/src/news.vala"
	_tmp23_ = g_strdup (_tmp22_);
#line 31 "/home/allen/Projects/news/src/news.vala"
	str = _tmp23_;
#line 33 "/home/allen/Projects/news/src/news.vala"
	itemIndex = 0;
#line 34 "/home/allen/Projects/news/src/news.vala"
	_tmp24_ = g_new0 (Article, 0);
#line 34 "/home/allen/Projects/news/src/news.vala"
	articles = _tmp24_;
#line 34 "/home/allen/Projects/news/src/news.vala"
	articles_length1 = 0;
#line 34 "/home/allen/Projects/news/src/news.vala"
	_articles_size_ = articles_length1;
#line 35 "/home/allen/Projects/news/src/news.vala"
	while (TRUE) {
#line 729 "news.c"
		const gchar* _tmp25_ = NULL;
		gint _tmp26_ = 0;
		gint _tmp27_ = 0;
		gint _tmp28_ = 0;
		gint startIndex = 0;
		const gchar* _tmp29_ = NULL;
		gint _tmp30_ = 0;
		gint _tmp31_ = 0;
		gint _tmp32_ = 0;
		gint _tmp33_ = 0;
		gint endIndex = 0;
		const gchar* _tmp34_ = NULL;
		gint _tmp35_ = 0;
		gint _tmp36_ = 0;
		gchar* s = NULL;
		const gchar* _tmp37_ = NULL;
		gint _tmp38_ = 0;
		gint _tmp39_ = 0;
		gchar* _tmp40_ = NULL;
		gint uStartIndex = 0;
		const gchar* _tmp41_ = NULL;
		gint _tmp42_ = 0;
		gint _tmp43_ = 0;
		gint _tmp44_ = 0;
		gint _tmp45_ = 0;
		const gchar* _tmp46_ = NULL;
		gint _tmp47_ = 0;
		gint _tmp48_ = 0;
		gint uEndIndex = 0;
		const gchar* _tmp49_ = NULL;
		gint _tmp50_ = 0;
		gint _tmp51_ = 0;
		gchar* uS = NULL;
		const gchar* _tmp52_ = NULL;
		gint _tmp53_ = 0;
		gint _tmp54_ = 0;
		gchar* _tmp55_ = NULL;
		gint dStartIndex = 0;
		const gchar* _tmp56_ = NULL;
		gint _tmp57_ = 0;
		gint _tmp58_ = 0;
		gint _tmp59_ = 0;
		gint _tmp60_ = 0;
		gint dEndIndex = 0;
		const gchar* _tmp61_ = NULL;
		gint _tmp62_ = 0;
		gint _tmp63_ = 0;
		gchar* dS = NULL;
		const gchar* _tmp64_ = NULL;
		gint _tmp65_ = 0;
		gint _tmp66_ = 0;
		gchar* _tmp67_ = NULL;
		gchar* _tmp68_ = NULL;
		gchar* _tmp69_ = NULL;
		gchar* _tmp70_ = NULL;
		gchar* _tmp71_ = NULL;
		gchar* _tmp72_ = NULL;
		gchar* _tmp73_ = NULL;
		gchar* _tmp74_ = NULL;
		gchar* _tmp75_ = NULL;
		gchar* _tmp76_ = NULL;
		gchar* _tmp77_ = NULL;
		gchar* _tmp78_ = NULL;
		gint eStartIndex = 0;
		const gchar* _tmp79_ = NULL;
		gint _tmp80_ = 0;
		gint _tmp81_ = 0;
		gint _tmp82_ = 0;
		gint eEndIndex = 0;
		const gchar* _tmp83_ = NULL;
		gint _tmp84_ = 0;
		gint _tmp85_ = 0;
		gchar* desc = NULL;
		const gchar* _tmp86_ = NULL;
		gint _tmp87_ = 0;
		gint _tmp88_ = 0;
		gchar* _tmp89_ = NULL;
		gchar* _tmp90_ = NULL;
		gchar* _tmp91_ = NULL;
		gchar* _tmp92_ = NULL;
		gchar* _tmp93_ = NULL;
		gchar* _tmp94_ = NULL;
		gchar* _tmp95_ = NULL;
		gchar* _tmp96_ = NULL;
		const gchar* _tmp97_ = NULL;
		gchar* _tmp98_ = NULL;
		gchar* _tmp99_ = NULL;
		gchar* _tmp100_ = NULL;
		Article article = {0};
		const gchar* _tmp101_ = NULL;
		gchar* _tmp102_ = NULL;
		const gchar* _tmp103_ = NULL;
		gchar* _tmp104_ = NULL;
		const gchar* _tmp105_ = NULL;
		gchar* _tmp106_ = NULL;
		Article _tmp107_ = {0};
		Article* _tmp108_ = NULL;
		gint _tmp108__length1 = 0;
		Article _tmp109_ = {0};
		Article _tmp110_ = {0};
#line 35 "/home/allen/Projects/news/src/news.vala"
		_tmp25_ = str;
#line 35 "/home/allen/Projects/news/src/news.vala"
		_tmp26_ = itemIndex;
#line 35 "/home/allen/Projects/news/src/news.vala"
		_tmp27_ = string_index_of (_tmp25_, "<item>", _tmp26_ + 1);
#line 35 "/home/allen/Projects/news/src/news.vala"
		itemIndex = (gint) _tmp27_;
#line 35 "/home/allen/Projects/news/src/news.vala"
		_tmp28_ = itemIndex;
#line 35 "/home/allen/Projects/news/src/news.vala"
		if (!(_tmp28_ != -1)) {
#line 35 "/home/allen/Projects/news/src/news.vala"
			break;
#line 844 "news.c"
		}
#line 36 "/home/allen/Projects/news/src/news.vala"
		_tmp29_ = str;
#line 36 "/home/allen/Projects/news/src/news.vala"
		_tmp30_ = itemIndex;
#line 36 "/home/allen/Projects/news/src/news.vala"
		_tmp31_ = string_index_of (_tmp29_, "<title>", _tmp30_);
#line 36 "/home/allen/Projects/news/src/news.vala"
		_tmp32_ = strlen ("<title>");
#line 36 "/home/allen/Projects/news/src/news.vala"
		_tmp33_ = _tmp32_;
#line 36 "/home/allen/Projects/news/src/news.vala"
		startIndex = _tmp31_ + _tmp33_;
#line 37 "/home/allen/Projects/news/src/news.vala"
		_tmp34_ = str;
#line 37 "/home/allen/Projects/news/src/news.vala"
		_tmp35_ = startIndex;
#line 37 "/home/allen/Projects/news/src/news.vala"
		_tmp36_ = string_index_of (_tmp34_, "</", _tmp35_);
#line 37 "/home/allen/Projects/news/src/news.vala"
		endIndex = _tmp36_;
#line 38 "/home/allen/Projects/news/src/news.vala"
		_tmp37_ = str;
#line 38 "/home/allen/Projects/news/src/news.vala"
		_tmp38_ = startIndex;
#line 38 "/home/allen/Projects/news/src/news.vala"
		_tmp39_ = endIndex;
#line 38 "/home/allen/Projects/news/src/news.vala"
		_tmp40_ = string_slice (_tmp37_, (glong) _tmp38_, (glong) _tmp39_);
#line 38 "/home/allen/Projects/news/src/news.vala"
		s = _tmp40_;
#line 41 "/home/allen/Projects/news/src/news.vala"
		_tmp41_ = str;
#line 41 "/home/allen/Projects/news/src/news.vala"
		_tmp42_ = itemIndex;
#line 41 "/home/allen/Projects/news/src/news.vala"
		_tmp43_ = string_index_of (_tmp41_, "<link>", _tmp42_);
#line 41 "/home/allen/Projects/news/src/news.vala"
		_tmp44_ = strlen ("<link>");
#line 41 "/home/allen/Projects/news/src/news.vala"
		_tmp45_ = _tmp44_;
#line 41 "/home/allen/Projects/news/src/news.vala"
		uStartIndex = _tmp43_ + _tmp45_;
#line 42 "/home/allen/Projects/news/src/news.vala"
		_tmp46_ = str;
#line 42 "/home/allen/Projects/news/src/news.vala"
		_tmp47_ = uStartIndex;
#line 42 "/home/allen/Projects/news/src/news.vala"
		_tmp48_ = string_index_of (_tmp46_, "url=", _tmp47_);
#line 42 "/home/allen/Projects/news/src/news.vala"
		uStartIndex = _tmp48_ + 4;
#line 43 "/home/allen/Projects/news/src/news.vala"
		_tmp49_ = str;
#line 43 "/home/allen/Projects/news/src/news.vala"
		_tmp50_ = uStartIndex;
#line 43 "/home/allen/Projects/news/src/news.vala"
		_tmp51_ = string_index_of (_tmp49_, "</", _tmp50_);
#line 43 "/home/allen/Projects/news/src/news.vala"
		uEndIndex = _tmp51_;
#line 44 "/home/allen/Projects/news/src/news.vala"
		_tmp52_ = str;
#line 44 "/home/allen/Projects/news/src/news.vala"
		_tmp53_ = uStartIndex;
#line 44 "/home/allen/Projects/news/src/news.vala"
		_tmp54_ = uEndIndex;
#line 44 "/home/allen/Projects/news/src/news.vala"
		_tmp55_ = string_slice (_tmp52_, (glong) _tmp53_, (glong) _tmp54_);
#line 44 "/home/allen/Projects/news/src/news.vala"
		uS = _tmp55_;
#line 47 "/home/allen/Projects/news/src/news.vala"
		_tmp56_ = str;
#line 47 "/home/allen/Projects/news/src/news.vala"
		_tmp57_ = itemIndex;
#line 47 "/home/allen/Projects/news/src/news.vala"
		_tmp58_ = string_index_of (_tmp56_, "<description>", _tmp57_);
#line 47 "/home/allen/Projects/news/src/news.vala"
		_tmp59_ = strlen ("<description>");
#line 47 "/home/allen/Projects/news/src/news.vala"
		_tmp60_ = _tmp59_;
#line 47 "/home/allen/Projects/news/src/news.vala"
		dStartIndex = _tmp58_ + _tmp60_;
#line 48 "/home/allen/Projects/news/src/news.vala"
		_tmp61_ = str;
#line 48 "/home/allen/Projects/news/src/news.vala"
		_tmp62_ = dStartIndex;
#line 48 "/home/allen/Projects/news/src/news.vala"
		_tmp63_ = string_index_of (_tmp61_, "</", _tmp62_);
#line 48 "/home/allen/Projects/news/src/news.vala"
		dEndIndex = _tmp63_;
#line 49 "/home/allen/Projects/news/src/news.vala"
		_tmp64_ = str;
#line 49 "/home/allen/Projects/news/src/news.vala"
		_tmp65_ = dStartIndex;
#line 49 "/home/allen/Projects/news/src/news.vala"
		_tmp66_ = dEndIndex;
#line 49 "/home/allen/Projects/news/src/news.vala"
		_tmp67_ = string_slice (_tmp64_, (glong) _tmp65_, (glong) _tmp66_);
#line 49 "/home/allen/Projects/news/src/news.vala"
		_tmp68_ = _tmp67_;
#line 49 "/home/allen/Projects/news/src/news.vala"
		_tmp69_ = string_replace (_tmp68_, "&quot;", "\"");
#line 49 "/home/allen/Projects/news/src/news.vala"
		_tmp70_ = _tmp69_;
#line 49 "/home/allen/Projects/news/src/news.vala"
		_tmp71_ = string_replace (_tmp70_, "&#39;", "'");
#line 49 "/home/allen/Projects/news/src/news.vala"
		_tmp72_ = _tmp71_;
#line 49 "/home/allen/Projects/news/src/news.vala"
		_tmp73_ = string_replace (_tmp72_, "&lt;", "<");
#line 49 "/home/allen/Projects/news/src/news.vala"
		_tmp74_ = _tmp73_;
#line 49 "/home/allen/Projects/news/src/news.vala"
		_tmp75_ = string_replace (_tmp74_, "&gt;", ">");
#line 49 "/home/allen/Projects/news/src/news.vala"
		_tmp76_ = _tmp75_;
#line 49 "/home/allen/Projects/news/src/news.vala"
		_tmp77_ = string_replace (_tmp76_, "&amp;", "&");
#line 49 "/home/allen/Projects/news/src/news.vala"
		_tmp78_ = _tmp77_;
#line 49 "/home/allen/Projects/news/src/news.vala"
		_g_free0 (_tmp76_);
#line 49 "/home/allen/Projects/news/src/news.vala"
		_g_free0 (_tmp74_);
#line 49 "/home/allen/Projects/news/src/news.vala"
		_g_free0 (_tmp72_);
#line 49 "/home/allen/Projects/news/src/news.vala"
		_g_free0 (_tmp70_);
#line 49 "/home/allen/Projects/news/src/news.vala"
		_g_free0 (_tmp68_);
#line 49 "/home/allen/Projects/news/src/news.vala"
		dS = _tmp78_;
#line 52 "/home/allen/Projects/news/src/news.vala"
		_tmp79_ = dS;
#line 52 "/home/allen/Projects/news/src/news.vala"
		_tmp80_ = string_index_of (_tmp79_, "</font><br><font size=\"-1\">", 0);
#line 52 "/home/allen/Projects/news/src/news.vala"
		_tmp81_ = strlen ("</font><br><font size=\"-1\">");
#line 52 "/home/allen/Projects/news/src/news.vala"
		_tmp82_ = _tmp81_;
#line 52 "/home/allen/Projects/news/src/news.vala"
		eStartIndex = _tmp80_ + _tmp82_;
#line 53 "/home/allen/Projects/news/src/news.vala"
		_tmp83_ = dS;
#line 53 "/home/allen/Projects/news/src/news.vala"
		_tmp84_ = eStartIndex;
#line 53 "/home/allen/Projects/news/src/news.vala"
		_tmp85_ = string_index_of (_tmp83_, "</", _tmp84_);
#line 53 "/home/allen/Projects/news/src/news.vala"
		eEndIndex = _tmp85_;
#line 54 "/home/allen/Projects/news/src/news.vala"
		_tmp86_ = dS;
#line 54 "/home/allen/Projects/news/src/news.vala"
		_tmp87_ = eStartIndex;
#line 54 "/home/allen/Projects/news/src/news.vala"
		_tmp88_ = eEndIndex;
#line 54 "/home/allen/Projects/news/src/news.vala"
		_tmp89_ = string_slice (_tmp86_, (glong) _tmp87_, (glong) _tmp88_);
#line 54 "/home/allen/Projects/news/src/news.vala"
		_tmp90_ = _tmp89_;
#line 54 "/home/allen/Projects/news/src/news.vala"
		_tmp91_ = string_replace (_tmp90_, "&nbsp;", " ");
#line 54 "/home/allen/Projects/news/src/news.vala"
		_tmp92_ = _tmp91_;
#line 54 "/home/allen/Projects/news/src/news.vala"
		_tmp93_ = string_replace (_tmp92_, "<b>", "");
#line 54 "/home/allen/Projects/news/src/news.vala"
		_tmp94_ = _tmp93_;
#line 54 "/home/allen/Projects/news/src/news.vala"
		_tmp95_ = string_replace (_tmp94_, "&#39;", "'");
#line 54 "/home/allen/Projects/news/src/news.vala"
		_tmp96_ = _tmp95_;
#line 54 "/home/allen/Projects/news/src/news.vala"
		_g_free0 (_tmp94_);
#line 54 "/home/allen/Projects/news/src/news.vala"
		_g_free0 (_tmp92_);
#line 54 "/home/allen/Projects/news/src/news.vala"
		_g_free0 (_tmp90_);
#line 54 "/home/allen/Projects/news/src/news.vala"
		desc = _tmp96_;
#line 55 "/home/allen/Projects/news/src/news.vala"
		_tmp97_ = desc;
#line 55 "/home/allen/Projects/news/src/news.vala"
		_tmp98_ = string_replace (_tmp97_, "&quot;", "\"");
#line 55 "/home/allen/Projects/news/src/news.vala"
		_tmp99_ = _tmp98_;
#line 55 "/home/allen/Projects/news/src/news.vala"
		_tmp100_ = string_replace (_tmp99_, "&middot;", ".");
#line 55 "/home/allen/Projects/news/src/news.vala"
		_g_free0 (desc);
#line 55 "/home/allen/Projects/news/src/news.vala"
		desc = _tmp100_;
#line 55 "/home/allen/Projects/news/src/news.vala"
		_g_free0 (_tmp99_);
#line 56 "/home/allen/Projects/news/src/news.vala"
		_tmp101_ = s;
#line 56 "/home/allen/Projects/news/src/news.vala"
		_tmp102_ = g_strdup (_tmp101_);
#line 56 "/home/allen/Projects/news/src/news.vala"
		_tmp103_ = desc;
#line 56 "/home/allen/Projects/news/src/news.vala"
		_tmp104_ = g_strdup (_tmp103_);
#line 56 "/home/allen/Projects/news/src/news.vala"
		_tmp105_ = uS;
#line 56 "/home/allen/Projects/news/src/news.vala"
		_tmp106_ = g_strdup (_tmp105_);
#line 56 "/home/allen/Projects/news/src/news.vala"
		memset (&_tmp107_, 0, sizeof (Article));
#line 56 "/home/allen/Projects/news/src/news.vala"
		_g_free0 (_tmp107_.title);
#line 56 "/home/allen/Projects/news/src/news.vala"
		_tmp107_.title = _tmp102_;
#line 56 "/home/allen/Projects/news/src/news.vala"
		_g_free0 (_tmp107_.text);
#line 56 "/home/allen/Projects/news/src/news.vala"
		_tmp107_.text = _tmp104_;
#line 56 "/home/allen/Projects/news/src/news.vala"
		_g_free0 (_tmp107_.link);
#line 56 "/home/allen/Projects/news/src/news.vala"
		_tmp107_.link = _tmp106_;
#line 56 "/home/allen/Projects/news/src/news.vala"
		article = _tmp107_;
#line 61 "/home/allen/Projects/news/src/news.vala"
		_tmp108_ = articles;
#line 61 "/home/allen/Projects/news/src/news.vala"
		_tmp108__length1 = articles_length1;
#line 61 "/home/allen/Projects/news/src/news.vala"
		_tmp109_ = article;
#line 61 "/home/allen/Projects/news/src/news.vala"
		article_copy (&_tmp109_, &_tmp110_);
#line 61 "/home/allen/Projects/news/src/news.vala"
		_vala_array_add1 (&articles, &articles_length1, &_articles_size_, &_tmp110_);
#line 35 "/home/allen/Projects/news/src/news.vala"
		article_destroy (&article);
#line 35 "/home/allen/Projects/news/src/news.vala"
		_g_free0 (desc);
#line 35 "/home/allen/Projects/news/src/news.vala"
		_g_free0 (dS);
#line 35 "/home/allen/Projects/news/src/news.vala"
		_g_free0 (uS);
#line 35 "/home/allen/Projects/news/src/news.vala"
		_g_free0 (s);
#line 1086 "news.c"
	}
#line 63 "/home/allen/Projects/news/src/news.vala"
	_tmp111_ = articles;
#line 63 "/home/allen/Projects/news/src/news.vala"
	_tmp111__length1 = articles_length1;
#line 63 "/home/allen/Projects/news/src/news.vala"
	if (result_length1) {
#line 63 "/home/allen/Projects/news/src/news.vala"
		*result_length1 = _tmp111__length1;
#line 1096 "news.c"
	}
#line 63 "/home/allen/Projects/news/src/news.vala"
	result = _tmp111_;
#line 63 "/home/allen/Projects/news/src/news.vala"
	_g_free0 (str);
#line 63 "/home/allen/Projects/news/src/news.vala"
	_g_string_free0 (text);
#line 63 "/home/allen/Projects/news/src/news.vala"
	_g_free0 (line);
#line 63 "/home/allen/Projects/news/src/news.vala"
	_g_object_unref0 (data_stream);
#line 63 "/home/allen/Projects/news/src/news.vala"
	_g_object_unref0 (youtube_page);
#line 63 "/home/allen/Projects/news/src/news.vala"
	return result;
#line 1112 "news.c"
}


static void _gtk_main_quit_gtk_widget_destroy (GtkWidget* _sender, gpointer self) {
#line 75 "/home/allen/Projects/news/src/news.vala"
	gtk_main_quit ();
#line 1119 "news.c"
}


static Block1Data* block1_data_ref (Block1Data* _data1_) {
#line 83 "/home/allen/Projects/news/src/news.vala"
	g_atomic_int_inc (&_data1_->_ref_count_);
#line 83 "/home/allen/Projects/news/src/news.vala"
	return _data1_;
#line 1128 "news.c"
}


static void block1_data_unref (void * _userdata_) {
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
#line 83 "/home/allen/Projects/news/src/news.vala"
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
#line 83 "/home/allen/Projects/news/src/news.vala"
		article_destroy (&_data1_->article);
#line 83 "/home/allen/Projects/news/src/news.vala"
		g_slice_free (Block1Data, _data1_);
#line 1141 "news.c"
	}
}


static gboolean _____lambda4_ (Block1Data* _data1_, GdkEventButton* e) {
	gboolean result = FALSE;
	GdkEventButton* _tmp0_ = NULL;
	GdkEventType _tmp1_ = 0;
	GError * _inner_error_ = NULL;
#line 106 "/home/allen/Projects/news/src/news.vala"
	g_return_val_if_fail (e != NULL, FALSE);
#line 107 "/home/allen/Projects/news/src/news.vala"
	_tmp0_ = e;
#line 107 "/home/allen/Projects/news/src/news.vala"
	_tmp1_ = _tmp0_->type;
#line 107 "/home/allen/Projects/news/src/news.vala"
	if (_tmp1_ == GDK_DOUBLE_BUTTON_PRESS) {
#line 1159 "news.c"
		gchar* _tmp2_ = NULL;
		Article _tmp3_ = {0};
		const gchar* _tmp4_ = NULL;
		gchar* _tmp5_ = NULL;
		gchar** _tmp6_ = NULL;
		gchar** _tmp7_ = NULL;
		gint _tmp7__length1 = 0;
		gchar** _tmp8_ = NULL;
		gchar** _tmp9_ = NULL;
		gchar** _tmp10_ = NULL;
		gint _tmp10__length1 = 0;
		GPid _tmp11_ = 0;
#line 108 "/home/allen/Projects/news/src/news.vala"
		_tmp2_ = g_strdup ("xdg-open");
#line 108 "/home/allen/Projects/news/src/news.vala"
		_tmp3_ = _data1_->article;
#line 108 "/home/allen/Projects/news/src/news.vala"
		_tmp4_ = _tmp3_.link;
#line 108 "/home/allen/Projects/news/src/news.vala"
		_tmp5_ = g_strdup (_tmp4_);
#line 108 "/home/allen/Projects/news/src/news.vala"
		_tmp6_ = g_new0 (gchar*, 2 + 1);
#line 108 "/home/allen/Projects/news/src/news.vala"
		_tmp6_[0] = _tmp2_;
#line 108 "/home/allen/Projects/news/src/news.vala"
		_tmp6_[1] = _tmp5_;
#line 108 "/home/allen/Projects/news/src/news.vala"
		_tmp7_ = _tmp6_;
#line 108 "/home/allen/Projects/news/src/news.vala"
		_tmp7__length1 = 2;
#line 108 "/home/allen/Projects/news/src/news.vala"
		_tmp9_ = _tmp8_ = g_get_environ ();
#line 108 "/home/allen/Projects/news/src/news.vala"
		_tmp10_ = _tmp9_;
#line 108 "/home/allen/Projects/news/src/news.vala"
		_tmp10__length1 = _vala_array_length (_tmp8_);
#line 108 "/home/allen/Projects/news/src/news.vala"
		g_spawn_async ("/", _tmp7_, _tmp10_, G_SPAWN_SEARCH_PATH, NULL, NULL, &_tmp11_, &_inner_error_);
#line 108 "/home/allen/Projects/news/src/news.vala"
		_data1_->child_pid = _tmp11_;
#line 108 "/home/allen/Projects/news/src/news.vala"
		_tmp10_ = (_vala_array_free (_tmp10_, _tmp10__length1, (GDestroyNotify) g_free), NULL);
#line 108 "/home/allen/Projects/news/src/news.vala"
		_tmp7_ = (_vala_array_free (_tmp7_, _tmp7__length1, (GDestroyNotify) g_free), NULL);
#line 108 "/home/allen/Projects/news/src/news.vala"
		if (G_UNLIKELY (_inner_error_ != NULL)) {
#line 1206 "news.c"
			gboolean _tmp12_ = FALSE;
#line 108 "/home/allen/Projects/news/src/news.vala"
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
#line 108 "/home/allen/Projects/news/src/news.vala"
			g_clear_error (&_inner_error_);
#line 108 "/home/allen/Projects/news/src/news.vala"
			return _tmp12_;
#line 1214 "news.c"
		}
	}
#line 116 "/home/allen/Projects/news/src/news.vala"
	result = FALSE;
#line 116 "/home/allen/Projects/news/src/news.vala"
	return result;
#line 1221 "news.c"
}


static gboolean ______lambda4__gtk_widget_button_press_event (GtkWidget* _sender, GdkEventButton* event, gpointer self) {
	gboolean result;
	result = _____lambda4_ (self, event);
#line 106 "/home/allen/Projects/news/src/news.vala"
	return result;
#line 1230 "news.c"
}


gint _vala_main (const gchar* args, int args_length1) {
	gint result = 0;
	Article* s = NULL;
	gint _tmp0_ = 0;
	Article* _tmp1_ = NULL;
	gint s_length1 = 0;
	gint _s_size_ = 0;
	GtkWindow* window = NULL;
	GtkWindow* _tmp2_ = NULL;
	GtkWindow* _tmp3_ = NULL;
	GtkWindow* _tmp4_ = NULL;
	GtkWindow* _tmp5_ = NULL;
	GtkWindow* _tmp6_ = NULL;
	GtkListBox* list = NULL;
	Article* _tmp7_ = NULL;
	gint _tmp7__length1 = 0;
	GtkWindow* _tmp47_ = NULL;
	GtkWindow* _tmp48_ = NULL;
#line 67 "/home/allen/Projects/news/src/news.vala"
	gtk_init (&args_length1, &args);
#line 69 "/home/allen/Projects/news/src/news.vala"
	_tmp1_ = fetch_news (&_tmp0_);
#line 69 "/home/allen/Projects/news/src/news.vala"
	s = _tmp1_;
#line 69 "/home/allen/Projects/news/src/news.vala"
	s_length1 = _tmp0_;
#line 69 "/home/allen/Projects/news/src/news.vala"
	_s_size_ = s_length1;
#line 71 "/home/allen/Projects/news/src/news.vala"
	_tmp2_ = (GtkWindow*) gtk_window_new (GTK_WINDOW_TOPLEVEL);
#line 71 "/home/allen/Projects/news/src/news.vala"
	g_object_ref_sink (_tmp2_);
#line 71 "/home/allen/Projects/news/src/news.vala"
	window = _tmp2_;
#line 72 "/home/allen/Projects/news/src/news.vala"
	_tmp3_ = window;
#line 72 "/home/allen/Projects/news/src/news.vala"
	gtk_window_set_title (_tmp3_, "News");
#line 73 "/home/allen/Projects/news/src/news.vala"
	_tmp4_ = window;
#line 73 "/home/allen/Projects/news/src/news.vala"
	gtk_window_set_position (_tmp4_, GTK_WIN_POS_CENTER);
#line 74 "/home/allen/Projects/news/src/news.vala"
	_tmp5_ = window;
#line 74 "/home/allen/Projects/news/src/news.vala"
	gtk_window_set_default_size (_tmp5_, 950, 950);
#line 75 "/home/allen/Projects/news/src/news.vala"
	_tmp6_ = window;
#line 75 "/home/allen/Projects/news/src/news.vala"
	g_signal_connect ((GtkWidget*) _tmp6_, "destroy", (GCallback) _gtk_main_quit_gtk_widget_destroy, NULL);
#line 77 "/home/allen/Projects/news/src/news.vala"
	list = NULL;
#line 79 "/home/allen/Projects/news/src/news.vala"
	_tmp7_ = s;
#line 79 "/home/allen/Projects/news/src/news.vala"
	_tmp7__length1 = s_length1;
#line 79 "/home/allen/Projects/news/src/news.vala"
	if (_tmp7_ == NULL) {
#line 1292 "news.c"
		GtkWindow* _tmp8_ = NULL;
		GtkLabel* _tmp9_ = NULL;
		GtkLabel* _tmp10_ = NULL;
#line 80 "/home/allen/Projects/news/src/news.vala"
		_tmp8_ = window;
#line 80 "/home/allen/Projects/news/src/news.vala"
		_tmp9_ = (GtkLabel*) gtk_label_new ("An error occured");
#line 80 "/home/allen/Projects/news/src/news.vala"
		g_object_ref_sink (_tmp9_);
#line 80 "/home/allen/Projects/news/src/news.vala"
		_tmp10_ = _tmp9_;
#line 80 "/home/allen/Projects/news/src/news.vala"
		gtk_container_add ((GtkContainer*) _tmp8_, (GtkWidget*) _tmp10_);
#line 80 "/home/allen/Projects/news/src/news.vala"
		_g_object_unref0 (_tmp10_);
#line 1308 "news.c"
	} else {
		GtkListBox* _tmp11_ = NULL;
		Article* _tmp12_ = NULL;
		gint _tmp12__length1 = 0;
		GtkWindow* _tmp45_ = NULL;
		GtkListBox* _tmp46_ = NULL;
#line 82 "/home/allen/Projects/news/src/news.vala"
		_tmp11_ = (GtkListBox*) gtk_list_box_new ();
#line 82 "/home/allen/Projects/news/src/news.vala"
		g_object_ref_sink (_tmp11_);
#line 82 "/home/allen/Projects/news/src/news.vala"
		_g_object_unref0 (list);
#line 82 "/home/allen/Projects/news/src/news.vala"
		list = _tmp11_;
#line 83 "/home/allen/Projects/news/src/news.vala"
		_tmp12_ = s;
#line 83 "/home/allen/Projects/news/src/news.vala"
		_tmp12__length1 = s_length1;
#line 1327 "news.c"
		{
			Article* article_collection = NULL;
			gint article_collection_length1 = 0;
			gint _article_collection_size_ = 0;
			gint article_it = 0;
#line 83 "/home/allen/Projects/news/src/news.vala"
			article_collection = _tmp12_;
#line 83 "/home/allen/Projects/news/src/news.vala"
			article_collection_length1 = _tmp12__length1;
#line 83 "/home/allen/Projects/news/src/news.vala"
			for (article_it = 0; article_it < _tmp12__length1; article_it = article_it + 1) {
#line 1339 "news.c"
				Article _tmp13_ = {0};
				Article article = {0};
#line 83 "/home/allen/Projects/news/src/news.vala"
				article_copy (&article_collection[article_it], &_tmp13_);
#line 83 "/home/allen/Projects/news/src/news.vala"
				article = _tmp13_;
#line 1346 "news.c"
				{
					Block1Data* _data1_;
					GtkBox* box = NULL;
					GtkBox* _tmp14_ = NULL;
					GtkBox* _tmp15_ = NULL;
					GtkLabel* label = NULL;
					GtkLabel* _tmp16_ = NULL;
					GtkLabel* _tmp17_ = NULL;
					Article _tmp18_ = {0};
					const gchar* _tmp19_ = NULL;
					gchar* _tmp20_ = NULL;
					gchar* _tmp21_ = NULL;
					gchar* _tmp22_ = NULL;
					gchar* _tmp23_ = NULL;
					GtkLabel* _tmp24_ = NULL;
					GtkBox* _tmp25_ = NULL;
					GtkLabel* _tmp26_ = NULL;
					GtkTextView* desc = NULL;
					GtkTextView* _tmp27_ = NULL;
					GtkTextView* _tmp28_ = NULL;
					GtkTextView* _tmp29_ = NULL;
					GtkTextBuffer* _tmp30_ = NULL;
					GtkTextBuffer* _tmp31_ = NULL;
					Article _tmp32_ = {0};
					const gchar* _tmp33_ = NULL;
					GtkTextView* _tmp34_ = NULL;
					GdkRGBA _tmp35_ = {0};
					GtkTextView* _tmp36_ = NULL;
					GtkBox* _tmp37_ = NULL;
					GtkTextView* _tmp38_ = NULL;
					GtkListBoxRow* row = NULL;
					GtkListBoxRow* _tmp39_ = NULL;
					GtkListBoxRow* _tmp40_ = NULL;
					GtkBox* _tmp41_ = NULL;
					GtkListBoxRow* _tmp42_ = NULL;
					GtkListBox* _tmp43_ = NULL;
					GtkListBoxRow* _tmp44_ = NULL;
#line 83 "/home/allen/Projects/news/src/news.vala"
					_data1_ = g_slice_new0 (Block1Data);
#line 83 "/home/allen/Projects/news/src/news.vala"
					_data1_->_ref_count_ = 1;
#line 83 "/home/allen/Projects/news/src/news.vala"
					_data1_->article = article;
#line 84 "/home/allen/Projects/news/src/news.vala"
					_tmp14_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
#line 84 "/home/allen/Projects/news/src/news.vala"
					g_object_ref_sink (_tmp14_);
#line 84 "/home/allen/Projects/news/src/news.vala"
					box = _tmp14_;
#line 85 "/home/allen/Projects/news/src/news.vala"
					_tmp15_ = box;
#line 85 "/home/allen/Projects/news/src/news.vala"
					g_object_set ((GtkWidget*) _tmp15_, "margin", 12, NULL);
#line 88 "/home/allen/Projects/news/src/news.vala"
					_tmp16_ = (GtkLabel*) gtk_label_new (NULL);
#line 88 "/home/allen/Projects/news/src/news.vala"
					g_object_ref_sink (_tmp16_);
#line 88 "/home/allen/Projects/news/src/news.vala"
					label = _tmp16_;
#line 89 "/home/allen/Projects/news/src/news.vala"
					_tmp17_ = label;
#line 89 "/home/allen/Projects/news/src/news.vala"
					_tmp18_ = _data1_->article;
#line 89 "/home/allen/Projects/news/src/news.vala"
					_tmp19_ = _tmp18_.title;
#line 89 "/home/allen/Projects/news/src/news.vala"
					_tmp20_ = g_strconcat ("<b>", _tmp19_, NULL);
#line 89 "/home/allen/Projects/news/src/news.vala"
					_tmp21_ = _tmp20_;
#line 89 "/home/allen/Projects/news/src/news.vala"
					_tmp22_ = g_strconcat (_tmp21_, "</b>", NULL);
#line 89 "/home/allen/Projects/news/src/news.vala"
					_tmp23_ = _tmp22_;
#line 89 "/home/allen/Projects/news/src/news.vala"
					gtk_label_set_markup (_tmp17_, _tmp23_);
#line 89 "/home/allen/Projects/news/src/news.vala"
					_g_free0 (_tmp23_);
#line 89 "/home/allen/Projects/news/src/news.vala"
					_g_free0 (_tmp21_);
#line 90 "/home/allen/Projects/news/src/news.vala"
					_tmp24_ = label;
#line 90 "/home/allen/Projects/news/src/news.vala"
					gtk_label_set_line_wrap (_tmp24_, TRUE);
#line 91 "/home/allen/Projects/news/src/news.vala"
					_tmp25_ = box;
#line 91 "/home/allen/Projects/news/src/news.vala"
					_tmp26_ = label;
#line 91 "/home/allen/Projects/news/src/news.vala"
					gtk_container_add ((GtkContainer*) _tmp25_, (GtkWidget*) _tmp26_);
#line 94 "/home/allen/Projects/news/src/news.vala"
					_tmp27_ = (GtkTextView*) gtk_text_view_new ();
#line 94 "/home/allen/Projects/news/src/news.vala"
					g_object_ref_sink (_tmp27_);
#line 94 "/home/allen/Projects/news/src/news.vala"
					desc = _tmp27_;
#line 95 "/home/allen/Projects/news/src/news.vala"
					_tmp28_ = desc;
#line 95 "/home/allen/Projects/news/src/news.vala"
					gtk_text_view_set_wrap_mode (_tmp28_, GTK_WRAP_WORD);
#line 96 "/home/allen/Projects/news/src/news.vala"
					_tmp29_ = desc;
#line 96 "/home/allen/Projects/news/src/news.vala"
					_tmp30_ = gtk_text_view_get_buffer (_tmp29_);
#line 96 "/home/allen/Projects/news/src/news.vala"
					_tmp31_ = _tmp30_;
#line 96 "/home/allen/Projects/news/src/news.vala"
					_tmp32_ = _data1_->article;
#line 96 "/home/allen/Projects/news/src/news.vala"
					_tmp33_ = _tmp32_.text;
#line 96 "/home/allen/Projects/news/src/news.vala"
					g_object_set (_tmp31_, "text", _tmp33_, NULL);
#line 97 "/home/allen/Projects/news/src/news.vala"
					_tmp34_ = desc;
#line 97 "/home/allen/Projects/news/src/news.vala"
					_tmp35_.red = (gdouble) 0;
#line 97 "/home/allen/Projects/news/src/news.vala"
					_tmp35_.green = (gdouble) 0;
#line 97 "/home/allen/Projects/news/src/news.vala"
					_tmp35_.blue = (gdouble) 0;
#line 97 "/home/allen/Projects/news/src/news.vala"
					_tmp35_.alpha = (gdouble) 0;
#line 97 "/home/allen/Projects/news/src/news.vala"
					gtk_widget_override_background_color ((GtkWidget*) _tmp34_, GTK_STATE_FLAG_NORMAL, &_tmp35_);
#line 98 "/home/allen/Projects/news/src/news.vala"
					_tmp36_ = desc;
#line 98 "/home/allen/Projects/news/src/news.vala"
					gtk_text_view_set_editable (_tmp36_, FALSE);
#line 100 "/home/allen/Projects/news/src/news.vala"
					_tmp37_ = box;
#line 100 "/home/allen/Projects/news/src/news.vala"
					_tmp38_ = desc;
#line 100 "/home/allen/Projects/news/src/news.vala"
					gtk_container_add ((GtkContainer*) _tmp37_, (GtkWidget*) _tmp38_);
#line 102 "/home/allen/Projects/news/src/news.vala"
					_tmp39_ = (GtkListBoxRow*) gtk_list_box_row_new ();
#line 102 "/home/allen/Projects/news/src/news.vala"
					g_object_ref_sink (_tmp39_);
#line 102 "/home/allen/Projects/news/src/news.vala"
					row = _tmp39_;
#line 104 "/home/allen/Projects/news/src/news.vala"
					_tmp40_ = row;
#line 104 "/home/allen/Projects/news/src/news.vala"
					_tmp41_ = box;
#line 104 "/home/allen/Projects/news/src/news.vala"
					gtk_container_add ((GtkContainer*) _tmp40_, (GtkWidget*) _tmp41_);
#line 105 "/home/allen/Projects/news/src/news.vala"
					_data1_->child_pid = (GPid) 0;
#line 106 "/home/allen/Projects/news/src/news.vala"
					_tmp42_ = row;
#line 106 "/home/allen/Projects/news/src/news.vala"
					g_signal_connect_data ((GtkWidget*) _tmp42_, "button-press-event", (GCallback) ______lambda4__gtk_widget_button_press_event, block1_data_ref (_data1_), (GClosureNotify) block1_data_unref, 0);
#line 119 "/home/allen/Projects/news/src/news.vala"
					_tmp43_ = list;
#line 119 "/home/allen/Projects/news/src/news.vala"
					_tmp44_ = row;
#line 119 "/home/allen/Projects/news/src/news.vala"
					gtk_container_add ((GtkContainer*) _tmp43_, (GtkWidget*) _tmp44_);
#line 83 "/home/allen/Projects/news/src/news.vala"
					_g_object_unref0 (row);
#line 83 "/home/allen/Projects/news/src/news.vala"
					_g_object_unref0 (desc);
#line 83 "/home/allen/Projects/news/src/news.vala"
					_g_object_unref0 (label);
#line 83 "/home/allen/Projects/news/src/news.vala"
					_g_object_unref0 (box);
#line 83 "/home/allen/Projects/news/src/news.vala"
					block1_data_unref (_data1_);
#line 83 "/home/allen/Projects/news/src/news.vala"
					_data1_ = NULL;
#line 1516 "news.c"
				}
			}
		}
#line 121 "/home/allen/Projects/news/src/news.vala"
		_tmp45_ = window;
#line 121 "/home/allen/Projects/news/src/news.vala"
		_tmp46_ = list;
#line 121 "/home/allen/Projects/news/src/news.vala"
		gtk_container_add ((GtkContainer*) _tmp45_, (GtkWidget*) _tmp46_);
#line 1526 "news.c"
	}
#line 123 "/home/allen/Projects/news/src/news.vala"
	_tmp47_ = window;
#line 123 "/home/allen/Projects/news/src/news.vala"
	gtk_widget_show_all ((GtkWidget*) _tmp47_);
#line 125 "/home/allen/Projects/news/src/news.vala"
	_tmp48_ = window;
#line 125 "/home/allen/Projects/news/src/news.vala"
	gtk_window_resize (_tmp48_, 950, 950);
#line 127 "/home/allen/Projects/news/src/news.vala"
	gtk_main ();
#line 128 "/home/allen/Projects/news/src/news.vala"
	result = 0;
#line 128 "/home/allen/Projects/news/src/news.vala"
	_g_object_unref0 (list);
#line 128 "/home/allen/Projects/news/src/news.vala"
	_g_object_unref0 (window);
#line 128 "/home/allen/Projects/news/src/news.vala"
	s = (_vala_Article_array_free (s, s_length1), NULL);
#line 128 "/home/allen/Projects/news/src/news.vala"
	return result;
#line 1548 "news.c"
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
#line 66 "/home/allen/Projects/news/src/news.vala"
	return _vala_main (argv, argc);
#line 1558 "news.c"
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



